In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3], 
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])


In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
#attributes
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim #dimentions

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10, size = (3,5))
random_array

array([[6, 1, 5, 2, 3],
       [2, 8, 1, 3, 5],
       [8, 2, 1, 3, 5]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.80909102, 0.34551903, 0.42762733],
       [0.77946756, 0.85023126, 0.11608543],
       [0.62257255, 0.43489268, 0.64281207],
       [0.55324893, 0.40809131, 0.65158993],
       [0.3501738 , 0.00534843, 0.46822565]])

In [26]:
random_array2.shape

(5, 3)

In [27]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.2126277 , 0.28362495, 0.8951913 ],
       [0.92141267, 0.49189525, 0.20580266],
       [0.50234004, 0.31928568, 0.91019645],
       [0.4109263 , 0.45804736, 0.97766045],
       [0.03060059, 0.68712887, 0.80246918]])

In [28]:
# pseudo-random numbers
np.random.seed(seed = 99999)
random_array4 = np.random.randint(10, size = (5, 3))
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [29]:
np.random.seed(seed = 0 )
random_array5 = np.random.random((5, 3))
random_array5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [30]:
random_array5 = np.random.random((5, 3))
random_array5

array([[0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

In [31]:
random_array5.shape

(5, 3)

# 3. Viewing arrays and matrixes

In [32]:
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [33]:
np.unique(random_array4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
a1[0]

1

In [39]:
a2[0]

array([1. , 2. , 3.3])

In [40]:
a2.shape

(2, 3)

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a2[1]

array([4. , 5. , 6.5])

In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [46]:
# a3[:2, :2, :2, :2] error

In [47]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9]],

        [[9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3]],

        [[7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7]]],


       [[[5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8]],

        [[2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8],
         [8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8]],

        [[2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8],
         [0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1]]]])

In [48]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [51]:
# Get the first 4 number of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 2, 7, 2],
         [0, 4, 5, 5],
         [8, 4, 1, 4],
         [8, 1, 1, 7]],

        [[9, 3, 6, 7],
         [0, 3, 5, 9],
         [4, 6, 4, 4],
         [4, 4, 8, 4]],

        [[7, 5, 5, 0],
         [5, 9, 3, 0],
         [0, 1, 2, 4],
         [0, 3, 2, 0]]],


       [[[5, 9, 0, 2],
         [2, 9, 2, 3],
         [2, 3, 4, 1],
         [9, 1, 4, 6]],

        [[2, 3, 0, 0],
         [0, 6, 3, 3],
         [8, 8, 2, 3],
         [0, 8, 8, 3]],

        [[2, 8, 4, 3],
         [4, 3, 6, 9],
         [0, 8, 5, 9],
         [9, 6, 5, 3]]]])

In [52]:
# Get the first 3 number of the inner most arrays
a4[:, :, :, :3]

array([[[[3, 2, 7],
         [0, 4, 5],
         [8, 4, 1],
         [8, 1, 1]],

        [[9, 3, 6],
         [0, 3, 5],
         [4, 6, 4],
         [4, 4, 8]],

        [[7, 5, 5],
         [5, 9, 3],
         [0, 1, 2],
         [0, 3, 2]]],


       [[[5, 9, 0],
         [2, 9, 2],
         [2, 3, 4],
         [9, 1, 4]],

        [[2, 3, 0],
         [0, 6, 3],
         [8, 8, 2],
         [0, 8, 8]],

        [[2, 8, 4],
         [4, 3, 6],
         [0, 8, 5],
         [9, 6, 5]]]])

In [53]:
# Get the first 2 number of the inner most arrays
a4[:, :, :, :2]

array([[[[3, 2],
         [0, 4],
         [8, 4],
         [8, 1]],

        [[9, 3],
         [0, 3],
         [4, 6],
         [4, 4]],

        [[7, 5],
         [5, 9],
         [0, 1],
         [0, 3]]],


       [[[5, 9],
         [2, 9],
         [2, 3],
         [9, 1]],

        [[2, 3],
         [0, 6],
         [8, 8],
         [0, 8]],

        [[2, 8],
         [4, 3],
         [0, 8],
         [9, 6]]]])

In [54]:
# Get the first 1 number of the inner most arrays
a4[:, :, :, :1]

array([[[[3],
         [0],
         [8],
         [8]],

        [[9],
         [0],
         [4],
         [4]],

        [[7],
         [5],
         [0],
         [0]]],


       [[[5],
         [2],
         [2],
         [9]],

        [[2],
         [0],
         [8],
         [0]],

        [[2],
         [4],
         [0],
         [9]]]])